kind: Deployment
apiVersion: apps/v1
metadata:
  name: smartsense-gaia-x-api
  annotations:
    app: backend
    configmap.reloader.stakater.com/reload: "smartsense-gaia-x-api"
    secret.reloader.stakater.com/reload: "smartsense-gaia-x-api"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: smartsense-gaia-x-api
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      name: smartsense-gaia-x-api
      labels:
        app: smartsense-gaia-x-api
    spec:
      containers:
        - name: smartsense-gaia-x-api
          image: smartsense-gaia-x-api
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: smartsense-gaia-x-api
            - configMapRef:
                name: smartsense-gaia-x-api
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8090
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 90
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8090
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 90

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim