apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-cluster-role
rules:
  - apiGroups:
      - ""
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
      - networking.k8s.io
    resources:
      - secrets
      - ingress
      - ingresses
      - services
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]